//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentList
    {
        public int AppointmentID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string CitizenName { get; set; }
        public string AppointmentStatus { get; set; }
    }
}
