//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int CitizenID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public byte AppointmentStatusID { get; set; }
        public Nullable<int> PoliticianID { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Politician Politician { get; set; }
    }
}
