//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citizen
    {
        public Citizen()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Volunteers = new HashSet<Volunteer>();
            this.PartyWorkers = new HashSet<PartyWorker>();
        }
    
        public int CitizenID { get; set; }
        public int ConstituencyID { get; set; }
        public string CitizenName { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public byte Gender { get; set; }
        public byte Age { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public byte CitizenType { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Volunteer> Volunteers { get; set; }
        public virtual Constituency Constituency { get; set; }
        public virtual ICollection<PartyWorker> PartyWorkers { get; set; }
    }
}
