//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public int CitizenID { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
