//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Constituency
    {
        public Constituency()
        {
            this.Citizens = new HashSet<Citizen>();
            this.Politicians = new HashSet<Politician>();
        }
    
        public int ConstituencyID { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string ConsituencyName { get; set; }
    
        public virtual ICollection<Citizen> Citizens { get; set; }
        public virtual ICollection<Politician> Politicians { get; set; }
    }
}
