//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int GalleryID { get; set; }
        public Nullable<int> PoliticianID { get; set; }
        public string AlbumName { get; set; }
        public string AlbumLink { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsVideo { get; set; }
        public string Place { get; set; }
        public string AlbumDescription { get; set; }
        public Nullable<int> AlbumId { get; set; }
    
        public virtual Politician Politician { get; set; }
    }
}
