//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyWorker
    {
        public int PartyWokerID { get; set; }
        public int CitizenID { get; set; }
        public int PoliticianID { get; set; }
        public short EventID { get; set; }
        public bool Status { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string Repassword { get; set; }
        public string Description { get; set; }
    
        public virtual Citizen Citizen { get; set; }
        public virtual Politician Politician { get; set; }
    }
}
