//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Politician
    {
        public Politician()
        {
            this.Galleries = new HashSet<Gallery>();
            this.Speeches = new HashSet<Speech>();
            this.Appointments = new HashSet<Appointment>();
            this.Events = new HashSet<Event>();
            this.PartyWorkers = new HashSet<PartyWorker>();
        }
    
        public int PoliticianID { get; set; }
        public Nullable<int> ConstituencyID { get; set; }
        public string PoliticianName { get; set; }
        public string MoblieNumber { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Age { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<byte> PoliticianType { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string PoliticanProfileUrl { get; set; }
    
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual ICollection<Speech> Speeches { get; set; }
        public virtual Constituency Constituency { get; set; }
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<PartyWorker> PartyWorkers { get; set; }
    }
}
