//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticalAppDBContext : DbContext
    {
        public PoliticalAppDBContext()
            : base("name=PoliticalAppDBContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<PoliticalParty> PoliticalParties { get; set; }
        public virtual DbSet<Volunteer> Volunteers { get; set; }
        public virtual DbSet<Citizen> Citizens { get; set; }
        public virtual DbSet<AppointmentList> AppointmentLists { get; set; }
        public virtual DbSet<AppointmentStatu> AppointmentStatus { get; set; }
        public virtual DbSet<ComplaintStatu> ComplaintStatus { get; set; }
        public virtual DbSet<Politician> Politicians { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Speech> Speeches { get; set; }
        public virtual DbSet<Constituency> Constituencies { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<PartyWorker> PartyWorkers { get; set; }
    }
}
