//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticalParty
    {
        public PoliticalParty()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int PoliticalPartyID { get; set; }
        public string PartyName { get; set; }
        public System.DateTime FoundedOn { get; set; }
        public string Address { get; set; }
        public string History { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string President { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
    }
}
