//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.PoliticalAppDataEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech
    {
        public short SpeechID { get; set; }
        public string SpeechName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SpeechDescription { get; set; }
        public string SpeechLink { get; set; }
        public bool IsVideo { get; set; }
        public string Place { get; set; }
        public Nullable<int> PoliticianID { get; set; }
    
        public virtual Politician Politician { get; set; }
    }
}
