--Drop Tables--------------
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'PoliticalParty')
	DROP TABLE  [PoliticalParty]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Constituency')
	DROP TABLE  [Constituency]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Event')
	DROP TABLE  [Event]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'AppointmentStatus')
	DROP TABLE  [AppointmentStatus]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'ComplaintStatus')
	DROP TABLE  [ComplaintStatus]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Appointment')
	BEGIN
	ALTER TABLE [Appointment] DROP CONSTRAINT [FK_Appintment_CitizenID]
	DROP TABLE  [Appointment]
	END
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Volunteer')
	DROP TABLE  [Volunteer]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Citizen')
	DROP TABLE  [Citizen]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'FeedBack')
	DROP TABLE  [FeedBack]
GO
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME= 'Complaint')
	DROP TABLE  [Complaint]
GO

--Create Tables----------
CREATE TABLE [PoliticalParty]
(
	[PoliticalPartyID] INT IDENTITY (1, 1) NOT NULL PRIMARY KEY,
	[PartyName] VARCHAR (100) NOT NULL,
	[President] VARCHAR (100) NOT NULL,
	[FoundedOn] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Address] VARCHAR(500) NOT NULL,
	[History] VARCHAR(500) NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [Constituency]
(
	[ConstituencyID] INT IDENTITY(1, 1) PRIMARY KEY,
	[ConstituencyName] DATETIME NOT NULL DEFAULT(GETDATE()),
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [Event]
(
	[EventID] INT IDENTITY (1, 1) PRIMARY KEY,
	[EventName] VARCHAR(100) NOT NULL,
	[PoliticalPartyID] INT NOT NULL,
	[PoliticianID] INT NOT NULL,
	[EventLocation] VARCHAR(100) NOT NULL,
	[EventBeginDate] DATETIME NOT NULL DEFAULT(GETDATE()),
	[EventEndDate] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Agenda] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(500) NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [Citizen]
(
	[CitizenID] INT IDENTITY(1, 1) PRIMARY KEY,
	[ConstituencyID] INT NOT NULL,
	[CitizenName] VARCHAR(100) NOT NULL,
	[MobileNumber] VARCHAR(15) NOT NULL,
	[Email] VARCHAR (250) NOT NULL,
	[Gender] TINYINT NOT NULL,
	[Age] TINYINT NOT NULL,
	[Address] VARCHAR(500) NOT NULL,
	[Description] VARCHAR(500) NOT NULL,
	[CitizenType] TINYINT NOT NULL,
	[AddedOn] DATETIME DEFAULT(GETDATE()),
	[UpdatedOn] DATETIME
)

CREATE TABLE [Volunteer]
(
	[VolunteerID] INT IDENTITY(1, 1) PRIMARY KEY,
	[CitizenID] INT NOT NULL,
	[EventID] INT NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME NOT NULL DEFAULT(GETDATE())
)

CREATE TABLE [FeedBack]
(
	[FeedBackID] INT IDENTITY(1, 1) PRIMARY KEY,
	[CitizenID] INT NOT NULL,
	[Subject] VARCHAR (100) NOT NULL,
	[Description] VARCHAR (500) NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [Complaint]
(
	[ComplaintID] INT IDENTITY(1,1) PRIMARY KEY,
	[CitizenID] INT NOT NULL,
	[Subject] VARCHAR(100) NOT NULL,
	[Description] VARCHAR(500) NOT NULL,
	[Status] TINYINT NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [Appointment]
(
	[AppointmentID] INT IDENTITY(1, 1) PRIMARY KEY,
	[CitizenID] INT NOT NULL,
	[AppointmentDate] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Message] VARCHAR(500) NOT NULL,
	[AppointmentStatusID] TINYINT NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [AppointmentStatus]
(
	[AppointmentStatusID] INT PRIMARY KEY,
	[AppointmentStatus] VARCHAR(20) NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME
)

CREATE TABLE [ComplaintStatus]
(
	[ComplaintStatusID] INT PRIMARY KEY,
	[ComplaintStatus] VARCHAR(20) NOT NULL,
	[AddedOn] DATETIME,
	[UpdatedOn] DATETIME

)

ALTER TABLE [Appointment] WITH CHECK ADD CONSTRAINT [FK_Appintment_CitizenID] FOREIGN KEY ([CitizenID])
REFERENCES  [Citizen]([CitizenID])
GO